ARG CROSS_BASE_IMAGE
FROM $CROSS_BASE_IMAGE

ENV PROTOC_VERSION=24.3

RUN apt-get update \
    && apt-get install -y libssl-dev pkg-config curl zip \
    && curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip \
    && unzip protoc-24.3-linux-x86_64.zip \
    && mv bin/protoc /usr/local/bin/protoc

