[target.x86_64-unknown-linux-gnu]
dockerfile = "./cross/Dockerfile.x86_64-unknown-linux-gnu+x86_64-pc-windows-gnu"
[target.x86_64-pc-windows-gnu]
dockerfile = "./cross/Dockerfile.x86_64-unknown-linux-gnu+x86_64-pc-windows-gnu"
