on:
  pull_request:
  push:
    branches:
      - main

name: CI

jobs:
  check:
    name: Run CI checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        run: rustup toolchain install stable --component rustfmt --component clippy

      - name: Formatting
        run: cargo fmt --all --check

      - name: Check
        run: cargo check --workspace

      - name: Clippy
        run: cargo clippy --all-features

      # - name: Audit dependencies
      #   run: cargo audit

      - name: Test
        run: cargo test

  success:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: success
    needs: ["check"]
    steps:
      - run: exit 1
        if: >-
          ${{ 
                contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
