on:
  workflow_dispatch:

name: Deploy NP server
jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: ./.github/actions/cargo-cache
      - uses: ./.github/actions/protoc

      - name: Install Rust toolchain
        run: rustup toolchain install stable

      - name: Set up host keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Add deployment key to ssh agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOYMENT_SSH_PRIVATE_KEY }}

      - name: Run deploy script
        run: ./nport-server/deploy/deploy.sh ${{ secrets.DEPLOYMENT_DESTINATION }}
